# Google OAuth2
oauth2.google.client-id=650482961530-ovjj63pmrnjn7kfafbeqidh00ivelo5i.apps.googleusercontent.com
oauth2.google.client-secret=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

# GitHub OAuth2
oauth2.github.client-id=Ov23lilrT122iI2qoD2H
oauth2.github.client-secret=7db2f8aa5ea002d1b1fb8177b7b614d968cb825c

# =============================================
# IMAGE SAVE IN CLOUDINARY
# =============================================
# ========== CLOUDINARY CONFIGURATION ==========
cloudinary.cloud-name=dpxksubxg
cloudinary.api-key=247265757794685
cloudinary.api-secret=ef_HKBJg3zaqs2YWtkqwfsBxJ2M